/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:dfa6c9fd-7e42-4f6e-a0d8-ba64721ab257",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Efq9IRLL4",
    "aws_user_pools_web_client_id": "2k6js40v20jbvc51h246shbs1g",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://lcw3lnqubbamfpigwjftlfpi3m.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-m3ispxvo7vbvdiutctrv7y42aa"
};


export default awsmobile;
